\c guacamole 

BEGIN;
CREATE ROLE guac WITH LOGIN PASSWORD 'C34CA980-F949-4CE9-ACB6-3C619F95EA5C';
GRANT CONNECT ON DATABASE guacamole TO guac;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA public TO guac;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO guac;
END;
