\c guacamole

BEGIN;
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA00','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA00.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training00');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB00','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB00.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training00');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC00','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC00.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training00');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA01','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA01.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training01');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA02','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA02.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training02');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA03','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA03.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training03');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA04','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA04.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training04');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA05','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA05.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training05');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA06','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA06.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training06');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA07','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA07.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training07');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA08','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA08.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training08');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA09','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA09.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training09');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA10','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA10.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training10');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA11','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA11.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training11');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA12','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA12.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training12');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA13','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA13.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training13');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA14','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA14.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training14');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA15','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA15.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training15');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA16','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA16.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training16');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA17','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA17.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training17');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA18','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA18.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training18');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA19','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA19.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training19');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA20','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA20.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training20');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA21','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA21.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training21');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA22','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA22.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training22');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA23','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA23.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training23');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA24','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA24.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training24');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA25','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA25.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training25');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidA26','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidA26.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training26');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB01','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB01.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training01');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB02','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB02.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training02');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB03','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB03.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training03');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB04','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB04.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training04');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB05','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB05.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training05');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB06','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB06.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training06');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB07','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB07.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training07');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB08','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB08.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training08');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB09','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB09.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training09');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB10','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB10.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training10');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB11','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB11.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training11');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB12','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB12.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training12');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB13','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB13.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training13');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB14','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB14.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training14');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB15','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB15.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training15');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB16','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB16.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training16');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB17','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB17.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training17');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB18','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB18.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training18');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB19','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB19.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training19');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB20','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB20.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training20');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB21','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB21.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training21');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB22','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB22.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training22');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB23','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB23.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training23');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB24','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB24.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training24');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB25','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB25.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training25');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidB26','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidB26.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training26');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC01','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC01.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training01');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC02','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC02.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training02');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC03','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC03.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training03');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC04','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC04.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training04');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC05','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC05.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training05');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC06','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC06.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training06');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC07','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC07.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training07');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC08','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC08.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training08');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC09','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC09.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training09');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC10','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC10.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training10');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC11','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC11.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training11');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC12','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC12.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training12');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC13','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC13.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training13');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC14','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC14.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training14');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC15','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC15.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training15');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC16','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC16.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training16');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC17','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC17.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training17');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC18','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC18.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training18');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC19','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC19.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training19');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC20','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC20.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training20');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC21','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC21.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training21');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC22','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC22.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training22');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC23','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC23.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training23');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC24','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC24.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training24');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC25','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC25.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training25');
INSERT INTO guacamole_connection (connection_name, protocol) VALUES ('fidC26','ssh'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'port','22'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'hostname','fidC26.training.vizuri.com'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'username','docker'); 
 INSERT INTO guacamole_connection_parameter VALUES(currval('guacamole_connection_connection_id_seq'),'password','training26');
END;
